- name: setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: create github runner user
  ansible.builtin.user:
    name: github

- name: create github actions folder
  ansible.builtin.file:
    group: github
    owner: github 
    path: /actions-runner
    state: directory

- name: download github runner
  ansible.builtin.unarchive: 
    src: https://github.com/actions/runner/releases/download/v2.328.0/actions-runner-linux-x64-2.328.0.tar.gz
    dest: /actions-runner
    owner: github
    group: github
    remote_src: yes
    
- name: python lib
  ansible.builtin.shell: #pip3.11 install ansible hvac
    name: hvac
    state: present
    executable: /usr/bin/pip3.11

- name: configure github runner
  ansible.builtin.shell: ./config.cmd --url https://github.com/Thippareddykishor --token {{ lookup('community.hashi_vault.hashi_vault', 'secret=infra/data/github-runner:RUNNER_TOKEN token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }}
  args:
    chdir: /actions-runner
  become_user: github