- name: setup prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: LVM
  ansible.builtin.include_role:
    name: common
    tasks_from: lvm

- name: check already runner configured
  ansible.builtin.stat:
    path: /actions-runner/.runner
  register: runner_stat

- name: Github actions setup
  when: not runner_stat.stat.exists
  block:
    - name: create github runner user
      ansible.builtin.user:
        name: github

    # - name: create github actions folder
    #   ansible.builtin.file:
    #     group: github
    #     owner: github 
    #     path: /actions-runner
    #     state: directory

    - name: Create github actions folder
      ansible.builtin.file:
        path: /actions-runner
        state: directory
        owner: github
        group: github

    - name: download github runner
      ansible.builtin.unarchive: 
        src:  https://github.com/actions/runner/releases/download/v2.328.0/actions-runner-linux-x64-2.328.0.tar.gz
        dest: /actions-runner
        owner: github
        group: github
        remote_src: yes

    - name: install libicu
      ansible.builtin.dnf:
        name: libicu
        state: present

    - name: debug
      ansible.builtin.debug:
        msg: " {{ runner_stat }} "

    - name: configure github runner
      ansible.builtin.shell: ./config.sh --url https://github.com/Thippareddykishor --token {{ lookup('community.hashi_vault.hashi_vault', 'secret=infra/data/github-runner:RUNNER_TOKEN token={{ vault_token }} url=http://vault-internal.kommanuthala.store:8200') }} --unattended
      args:
        chdir: /actions-runner
      become_user: github
      when: not runner_stat.stat.exists

    - name: copy service file
      ansible.builtin.template:
        src: github-runner.service
        dest: /etc/systemd/system/github-runner.service

- name: start github service
  ansible.builtin.systemd_service:
    name: github-runner
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: copy hashi repo file
  ansible.builtin.template:
    src: hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install terraform
  ansible.builtin.dnf:
    name: terraform
    state: installed

- name: copy kubectl repo file
  ansible.builtin.template:
    src: kubernets.repo
    dest: /etc/yum.repos.d/kubernets.repo

- name: install kubectl
  ansible.builtin.dnf:
    name: kubectl
    state: installed

- name: Install Helm
  ansible.builtin.shell: |
    curl -L -O https://get.helm.sh/helm-v3.17.2-linux-amd64.tar.gz
    tar -xf helm-v3.17.2-linux-amd64.tar.gz
    mv linux-amd64/helm /bin/helm
  args:
    chdir: /tmp

- name: Get docker repo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Add github user to docker group
  ansible.builtin.user:
    name: github
    groups: docker

- name: enable nodejs 
  ansible.builtin.shell:
    dnf module disable nodejs -y ; dnf module enable nodejs:20 -y

- name: enable node js module
  ansible.builtin.dnf:
    name: nodejs

- name: install maven
  ansible.builtin.dnf:
    name: maven

