- name: set prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: LVM layout
  ansible.builtin.include_role: 
    name: common
    tasks_from: lvm

- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repod.d/elastic.repo

- name: install ELK
  ansible.builtin.dnf:
    name: 
      - elasticsearch
      - kibana
      - logstash
      - nginx
    state: present

- name: Copy nginx file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: start ELK   
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx