- name: set prompt
  ansible.builtin.shell:
    set-prompt {{ tool_name }}

- name: download repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: install vault
  ansible.builtin.dnf:
    name: vault
    state: present
  
- name: Copy vault config
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl

- name: start vault
  ansible.builtin.systemd_service:
    state: started
    enabled: yes
    name: vault